import type { Metadata } from "next";
import '@/app/ui/global.css';
import { lato } from "@/app/ui/fonts";


export const metadata: Metadata = {
  title: "GDI Hackathon 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-white">
      <body
        className={`${lato.className} antialiased h-full`}
      >
        {children}
      </body>
    </html>
  );
}
